### ISSUE TITLE
Wishlist for Admin tab

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/LaunchPod#44]
Since we're wanting this to be super forkable, it would be nice to make the admin side of things as easy as possible.  Here is my wish list for a new Admin tab with better UX:

- Display all the active streams in a similar way to the home page, but with an edit stream (pencil) and delete (Trashcan? red strike through) icons that will call the update stream or delete stream functions.  The update should pop up a modal similar to how it currently looks.  The delete should give them a warning saying something like "Are you sure you want to delete the stream at address: 0x...).

- Near(or in) the active streams section should be an Add Creators button.  This opens the current modal that is used for the Add Batch Creators, but it should have one blank creator info entry already visible, along with the Add button.  If they only enter one creator, it will call addCreatorFlow, if they enter multiple entries, it should call addBatch.

- Display a list of all admins, with the same delete icon as mentioned above to remove an admin, with a similar warning message.  An Add Admin button should be in this section that pops up the add admin modal.

- Display the contract balance similar to the front page, and near that is the Fund Contract button to open that modal.  In this same section should be a Rescue Funds button that will open that model to rescue either the ETH or the ERC20.  Is this possible or does it have to be two buttons? 

Note that in all these modals there won't be a drop down menu at the top anymore since all functions will be accounted for in the UI.

I am hoping that we can recycle much of the UI that already exists to make this a bit easier, but let me know your thoughts or questions.  Thank you!

**Comment by 0xChijoke** [comment]
gm,

I've started working on the changes you've mentioned, including displaying active streams with edit and delete icons, listing admins with delete options, and displaying contract balance and fund buttons (rescue in progress).

However, I want to acknowledge that the branch I'm working on to address these changes might introduce some bugs due to the extensive folder structure modifications. While I'm making efforts to ensure stability, there might still be some issues that arise. Could you check it out here? https://github.com/BuidlGuidl/LaunchPod/tree/wishQuest

I'm looking forward to your feedback on the work done so far, and please feel share your thoughts or questions. Thank you for your guidance and support as we enhance the app!
